name: login_auth
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  camera: ^0.10.5+9
  dio: ^5.0.0
  image_picker: ^0.8.5+3
  flutter_tflite: ^1.0.1
  file_picker: ^6.1.1
  image_picker_web: ^3.1.1
  http: ^1.2.0
  url_launcher: ^6.2.4
  image: ^3.0.1
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.9
  dotted_border: ^2.1.0
  logger: ^2.0.2+1
  flutter_vision: ^1.1.4
  google_sign_in: ^6.2.1
  flutter_spinkit: ^5.2.0
  provider: ^6.1.1
  animated_text_kit: ^4.2.2
  flutter_speed_dial: ^7.0.0
  speech_to_text: ^6.6.0
  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_translation: ^0.9.0
  dash_chat_2: ^0.0.20
  chat_gpt_sdk: ^3.0.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/models/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.ttf
        - asset: assets/fonts/NotoSansKR-Bold.ttf
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
        - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
        - asset: assets/fonts/NotoSansKR-Light.ttf
        - asset: assets/fonts/NotoSansKR-Medium.ttf
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
        - asset: assets/fonts/NotoSansKR-Thin.ttf
        - asset: assets/fonts/NotoSansKR-VariableFont_wght.ttf
